name: generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"   # her gün gece çalışsın
  workflow_dispatch:       # Actions sekmesinden elle tetiklemek için
  push:
    branches:
      - main               # repo'nun default branch'i "master" ise burayı master yap

permissions:
  contents: write          # output branch'ine push için gerekli

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: mozybali
          outputs: |
            dist/github-contribution-snake.svg
            dist/github-contribution-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push snake SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
